baseURL = ""
languageCode = 'en-us'
theme = "coming-soon"

[params]
    title = "Новый Год" 
    description = ""
    favicon = ""
    message = "УЖЕ СКОРО!!!" 
    release = "Jan 01, 2025" 
    background = "" 

socialIcons = [
#    {name = "email", url = "example@example.com"},      
#    {name = "twitter", url = "https://twitter.com/"},    
#    {name = "facebook", url = "https://facebook.com/"},    
#    {name = "github", url = "https://github.com/"},    
#    {name = "instagram", url = "https://instagram.com/"},    
#    {name = "tiktok", url = "https://tiktok.com/"},    
#    {name = "linkedin", url = "https://linkedin.com/"},    
] 

[params.twitter]
	enable = false 
	username = ""
