# Информация о проекте
site_name: ParisKomm.uz
site_url: https://shaburoff.github.io/
site_author: Игорь Шабуров
site_description: >-
  Фотоархив прошедших лет

# Репозиторий
repo_name: shaburoff.github.io
repo_url: https://github.com/shaburoff/shaburoff.github.io
edit_uri: edit/main/docs/

# Авторское право
copyright: Copyright &copy; 2022~2023 Shaburoff/All Rights Reserved.

# Конфигурация
theme:
  name: material
  language: ru
  custom_dir: overrides
  features: 
    - content.action.edit
    - content.action.view
    # - announce.dismiss
    # - header.autohide
    # - navigation.expand
    - navigation.footer
    - navigation.indexes
    # - navigation.instant
    # - navigation.instant.prefetch
    # - navigation.instant.progress
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate   
  palette:
    # Светлый режим
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Переключить в темный режим
    # Тёмный режим
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Переключить в светлый режим
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  icon:
    logo: material/image-multiple-outline
  
# Дополнительная конфигурация
extra:
  social:
    - icon: fontawesome/solid/house
      link: https://shaburoff.github.io/

    - icon: fontawesome/brands/telegram 
      link: https://t.me/+kbL3i1FBI_1iYWNi

    - icon: fontawesome/brands/vk
      link: https://vk.com/

    - icon: fontawesome/solid/envelope
      link: mailto:<shaburoff@internet.ru>

# Плагины
plugins:
  - blog:
      blog_toc: true
      categories_url_format: "category/{slug}"
      categories_slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
      draft: false
      draft_if_future_date: true
      pagination_per_page: 5
      pagination_url_format: "page/{page}"
      pagination_format: "$link_first $link_previous ~2~ $link_next $link_last"
      pagination_if_single_page: true
      pagination_keep_content: true
      post_date_format: long
      post_url_format: "{slug}"
      post_excerpt_separator: <!-- more -->
      post_slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - git-revision-date-localized:
      enable_creation_date: false
      type: date
      timezone: Asia/Tashkent
      locale: ru
      exclude:
        - index.md
        - tags.md
  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      slide_effect: slide
      width: 100%
      height: auto
      zoomable: true
      draggable: true
      skip_classes:
        - skip-lightbox
      auto_caption: false
      caption_position: bottom
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - social
  - tags:
      tags_file: tags.md

# Хуки

hooks:
  - overrides/hooks/shortcodes.py
  - overrides/hooks/translations.py

# Расширения
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - tables
  - toc:
      permalink: true
      permalink_title: Ссылка на раздел
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.critic:
      mode: view
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: shaburoff
      repo: shaburoff.github.io
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true

# Навигация

nav:
  - Главная: index.md
  - Блог:
    - blog/index.md
    - Теги: tags.md
  - Сведения:
    - overview/index.md
    - События:
      - Обновление сайта: overview/events/page-1.md
    - Новости:
      - 29.11.2023: overview/news/page-3.md
      - Обновление: overview/news/page-4.md
    - О сайте: overview/about.md

    